name: 1 on 1
on:
  schedule:
    - cron: 0 9 * * 1

jobs:
  create-sprint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workspace
        uses: actions/checkout@master
      - name: Create weekly 1:1 issue
        uses: JasonEtco/create-an-issue@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/1:1.md
